### ISSUE TITLE
SwaggerUI 

### ISSUE THREAD

**Issue by worasit** [worasit/NongpedAPI#19]
> As a developer, I want a swaggerUI page, so that I can use them to publish NongpedAPI usage.

## Acceptance Criteria:
Having SwaggerUI page hosting on URL 'http://host:4000'

**Comment by worasit** [comment]
<img width="1009" alt="screen shot 2016-12-25 at 6 59 40 pm" src="https://cloud.githubusercontent.com/assets/8605593/21471102/2a8c3fac-cad7-11e6-93c5-d9f06aece196.png">

**Comment by ghost** [comment]
Ugly shit UI!
